apiVersion: apps/v1
kind: Deployment
metadata:
  name: move-pair
  namespace: kubemove
spec:
  replicas: 1
  selector:
    matchLabels:
      name: move-pair
  template:
    metadata:
      labels:
        name: move-pair
    spec:
      serviceAccountName: kubemove
      containers:
      - name: move-pair
        # Replace this with the built image name
        image: ${REGISTRY}/move-pair:ci
        imagePullPolicy: IfNotPresent
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
